/* soapMESServiceSoapProxy.cpp
   Generated by gSOAP 2.8.64 for MESService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapMESServiceSoapProxy.h"

MESServiceSoapProxy::MESServiceSoapProxy() : soap(SOAP_IO_DEFAULT)
{	MESServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

MESServiceSoapProxy::MESServiceSoapProxy(const MESServiceSoapProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
}

MESServiceSoapProxy::MESServiceSoapProxy(const struct soap &_soap) : soap(_soap)
{ }

MESServiceSoapProxy::MESServiceSoapProxy(const char *endpoint) : soap(SOAP_IO_DEFAULT)
{	MESServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

MESServiceSoapProxy::MESServiceSoapProxy(soap_mode iomode) : soap(iomode)
{	MESServiceSoapProxy_init(iomode, iomode);
}

MESServiceSoapProxy::MESServiceSoapProxy(const char *endpoint, soap_mode iomode) : soap(iomode)
{	MESServiceSoapProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

MESServiceSoapProxy::MESServiceSoapProxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	MESServiceSoapProxy_init(imode, omode);
}

MESServiceSoapProxy::~MESServiceSoapProxy()
{
	this->destroy();
	}

void MESServiceSoapProxy::MESServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"tempuri", "http://tempuri.org/", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this, namespaces);
}

MESServiceSoapProxy *MESServiceSoapProxy::copy()
{	MESServiceSoapProxy *dup = SOAP_NEW_UNMANAGED(MESServiceSoapProxy(*(struct soap*)this));
	return dup;
}

MESServiceSoapProxy& MESServiceSoapProxy::operator=(const MESServiceSoapProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void MESServiceSoapProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void MESServiceSoapProxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	MESServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void MESServiceSoapProxy::soap_noheader()
{	this->header = NULL;
}

::SOAP_ENV__Header *MESServiceSoapProxy::soap_header()
{	return this->header;
}

::SOAP_ENV__Fault *MESServiceSoapProxy::soap_fault()
{	return this->fault;
}

const char *MESServiceSoapProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *MESServiceSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int MESServiceSoapProxy::soap_close_socket()
{	return soap_closesock(this);
}

int MESServiceSoapProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void MESServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void MESServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *MESServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int MESServiceSoapProxy::GetDate(const char *endpoint, const char *soap_action, _tempuri__GetDate *tempuri__GetDate, _tempuri__GetDateResponse &tempuri__GetDateResponse)
{	struct soap *soap = this;
	struct __tempuri__GetDate soap_tmp___tempuri__GetDate;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetDate";
	soap_tmp___tempuri__GetDate.tempuri__GetDate = tempuri__GetDate;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetDate(soap, &soap_tmp___tempuri__GetDate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetDate(soap, &soap_tmp___tempuri__GetDate, "-tempuri:GetDate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetDate(soap, &soap_tmp___tempuri__GetDate, "-tempuri:GetDate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetDateResponse*>(&tempuri__GetDateResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetDateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetDateResponse.soap_get(soap, "tempuri:GetDateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::GetDocCode(const char *endpoint, const char *soap_action, _tempuri__GetDocCode *tempuri__GetDocCode, _tempuri__GetDocCodeResponse &tempuri__GetDocCodeResponse)
{	struct soap *soap = this;
	struct __tempuri__GetDocCode soap_tmp___tempuri__GetDocCode;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetDocCode";
	soap_tmp___tempuri__GetDocCode.tempuri__GetDocCode = tempuri__GetDocCode;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetDocCode(soap, &soap_tmp___tempuri__GetDocCode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetDocCode(soap, &soap_tmp___tempuri__GetDocCode, "-tempuri:GetDocCode", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetDocCode(soap, &soap_tmp___tempuri__GetDocCode, "-tempuri:GetDocCode", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetDocCodeResponse*>(&tempuri__GetDocCodeResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetDocCodeResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetDocCodeResponse.soap_get(soap, "tempuri:GetDocCodeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::ToolingTimes(const char *endpoint, const char *soap_action, _tempuri__ToolingTimes *tempuri__ToolingTimes, _tempuri__ToolingTimesResponse &tempuri__ToolingTimesResponse)
{	struct soap *soap = this;
	struct __tempuri__ToolingTimes soap_tmp___tempuri__ToolingTimes;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ToolingTimes";
	soap_tmp___tempuri__ToolingTimes.tempuri__ToolingTimes = tempuri__ToolingTimes;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__ToolingTimes(soap, &soap_tmp___tempuri__ToolingTimes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__ToolingTimes(soap, &soap_tmp___tempuri__ToolingTimes, "-tempuri:ToolingTimes", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__ToolingTimes(soap, &soap_tmp___tempuri__ToolingTimes, "-tempuri:ToolingTimes", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__ToolingTimesResponse*>(&tempuri__ToolingTimesResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__ToolingTimesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__ToolingTimesResponse.soap_get(soap, "tempuri:ToolingTimesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::WorkOrder(const char *endpoint, const char *soap_action, _tempuri__WorkOrder *tempuri__WorkOrder, _tempuri__WorkOrderResponse &tempuri__WorkOrderResponse)
{	struct soap *soap = this;
	struct __tempuri__WorkOrder soap_tmp___tempuri__WorkOrder;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/WorkOrder";
	soap_tmp___tempuri__WorkOrder.tempuri__WorkOrder = tempuri__WorkOrder;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__WorkOrder(soap, &soap_tmp___tempuri__WorkOrder);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__WorkOrder(soap, &soap_tmp___tempuri__WorkOrder, "-tempuri:WorkOrder", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__WorkOrder(soap, &soap_tmp___tempuri__WorkOrder, "-tempuri:WorkOrder", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__WorkOrderResponse*>(&tempuri__WorkOrderResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__WorkOrderResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__WorkOrderResponse.soap_get(soap, "tempuri:WorkOrderResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::LineInventory(const char *endpoint, const char *soap_action, _tempuri__LineInventory *tempuri__LineInventory, _tempuri__LineInventoryResponse &tempuri__LineInventoryResponse)
{	struct soap *soap = this;
	struct __tempuri__LineInventory soap_tmp___tempuri__LineInventory;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/LineInventory";
	soap_tmp___tempuri__LineInventory.tempuri__LineInventory = tempuri__LineInventory;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__LineInventory(soap, &soap_tmp___tempuri__LineInventory);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__LineInventory(soap, &soap_tmp___tempuri__LineInventory, "-tempuri:LineInventory", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__LineInventory(soap, &soap_tmp___tempuri__LineInventory, "-tempuri:LineInventory", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LineInventoryResponse*>(&tempuri__LineInventoryResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LineInventoryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LineInventoryResponse.soap_get(soap, "tempuri:LineInventoryResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::LineInventoryUpdate(const char *endpoint, const char *soap_action, _tempuri__LineInventoryUpdate *tempuri__LineInventoryUpdate, _tempuri__LineInventoryUpdateResponse &tempuri__LineInventoryUpdateResponse)
{	struct soap *soap = this;
	struct __tempuri__LineInventoryUpdate soap_tmp___tempuri__LineInventoryUpdate;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/LineInventoryUpdate";
	soap_tmp___tempuri__LineInventoryUpdate.tempuri__LineInventoryUpdate = tempuri__LineInventoryUpdate;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__LineInventoryUpdate(soap, &soap_tmp___tempuri__LineInventoryUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__LineInventoryUpdate(soap, &soap_tmp___tempuri__LineInventoryUpdate, "-tempuri:LineInventoryUpdate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__LineInventoryUpdate(soap, &soap_tmp___tempuri__LineInventoryUpdate, "-tempuri:LineInventoryUpdate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LineInventoryUpdateResponse*>(&tempuri__LineInventoryUpdateResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LineInventoryUpdateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LineInventoryUpdateResponse.soap_get(soap, "tempuri:LineInventoryUpdateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::LineInventoryReturn(const char *endpoint, const char *soap_action, _tempuri__LineInventoryReturn *tempuri__LineInventoryReturn, _tempuri__LineInventoryReturnResponse &tempuri__LineInventoryReturnResponse)
{	struct soap *soap = this;
	struct __tempuri__LineInventoryReturn soap_tmp___tempuri__LineInventoryReturn;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/LineInventoryReturn";
	soap_tmp___tempuri__LineInventoryReturn.tempuri__LineInventoryReturn = tempuri__LineInventoryReturn;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__LineInventoryReturn(soap, &soap_tmp___tempuri__LineInventoryReturn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__LineInventoryReturn(soap, &soap_tmp___tempuri__LineInventoryReturn, "-tempuri:LineInventoryReturn", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__LineInventoryReturn(soap, &soap_tmp___tempuri__LineInventoryReturn, "-tempuri:LineInventoryReturn", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LineInventoryReturnResponse*>(&tempuri__LineInventoryReturnResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LineInventoryReturnResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LineInventoryReturnResponse.soap_get(soap, "tempuri:LineInventoryReturnResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::ItemsAdd(const char *endpoint, const char *soap_action, _tempuri__ItemsAdd *tempuri__ItemsAdd, _tempuri__ItemsAddResponse &tempuri__ItemsAddResponse)
{	struct soap *soap = this;
	struct __tempuri__ItemsAdd soap_tmp___tempuri__ItemsAdd;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ItemsAdd";
	soap_tmp___tempuri__ItemsAdd.tempuri__ItemsAdd = tempuri__ItemsAdd;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__ItemsAdd(soap, &soap_tmp___tempuri__ItemsAdd);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__ItemsAdd(soap, &soap_tmp___tempuri__ItemsAdd, "-tempuri:ItemsAdd", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__ItemsAdd(soap, &soap_tmp___tempuri__ItemsAdd, "-tempuri:ItemsAdd", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__ItemsAddResponse*>(&tempuri__ItemsAddResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__ItemsAddResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__ItemsAddResponse.soap_get(soap, "tempuri:ItemsAddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::DocAdd(const char *endpoint, const char *soap_action, _tempuri__DocAdd *tempuri__DocAdd, _tempuri__DocAddResponse &tempuri__DocAddResponse)
{	struct soap *soap = this;
	struct __tempuri__DocAdd soap_tmp___tempuri__DocAdd;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/DocAdd";
	soap_tmp___tempuri__DocAdd.tempuri__DocAdd = tempuri__DocAdd;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__DocAdd(soap, &soap_tmp___tempuri__DocAdd);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__DocAdd(soap, &soap_tmp___tempuri__DocAdd, "-tempuri:DocAdd", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__DocAdd(soap, &soap_tmp___tempuri__DocAdd, "-tempuri:DocAdd", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__DocAddResponse*>(&tempuri__DocAddResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__DocAddResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__DocAddResponse.soap_get(soap, "tempuri:DocAddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::GetDept(const char *endpoint, const char *soap_action, _tempuri__GetDept *tempuri__GetDept, _tempuri__GetDeptResponse &tempuri__GetDeptResponse)
{	struct soap *soap = this;
	struct __tempuri__GetDept soap_tmp___tempuri__GetDept;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetDept";
	soap_tmp___tempuri__GetDept.tempuri__GetDept = tempuri__GetDept;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetDept(soap, &soap_tmp___tempuri__GetDept);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetDept(soap, &soap_tmp___tempuri__GetDept, "-tempuri:GetDept", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetDept(soap, &soap_tmp___tempuri__GetDept, "-tempuri:GetDept", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetDeptResponse*>(&tempuri__GetDeptResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetDeptResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetDeptResponse.soap_get(soap, "tempuri:GetDeptResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::GetPower(const char *endpoint, const char *soap_action, _tempuri__GetPower *tempuri__GetPower, _tempuri__GetPowerResponse &tempuri__GetPowerResponse)
{	struct soap *soap = this;
	struct __tempuri__GetPower soap_tmp___tempuri__GetPower;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetPower";
	soap_tmp___tempuri__GetPower.tempuri__GetPower = tempuri__GetPower;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetPower(soap, &soap_tmp___tempuri__GetPower);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetPower(soap, &soap_tmp___tempuri__GetPower, "-tempuri:GetPower", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetPower(soap, &soap_tmp___tempuri__GetPower, "-tempuri:GetPower", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetPowerResponse*>(&tempuri__GetPowerResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetPowerResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetPowerResponse.soap_get(soap, "tempuri:GetPowerResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::Login(const char *endpoint, const char *soap_action, _tempuri__Login *tempuri__Login, _tempuri__LoginResponse &tempuri__LoginResponse)
{	struct soap *soap = this;
	struct __tempuri__Login soap_tmp___tempuri__Login;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Login";
	soap_tmp___tempuri__Login.tempuri__Login = tempuri__Login;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Login(soap, &soap_tmp___tempuri__Login);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Login(soap, &soap_tmp___tempuri__Login, "-tempuri:Login", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Login(soap, &soap_tmp___tempuri__Login, "-tempuri:Login", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LoginResponse*>(&tempuri__LoginResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LoginResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LoginResponse.soap_get(soap, "tempuri:LoginResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan1Send(const char *endpoint, const char *soap_action, _tempuri__AnDan1Send *tempuri__AnDan1Send, _tempuri__AnDan1SendResponse &tempuri__AnDan1SendResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan1Send soap_tmp___tempuri__AnDan1Send;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan1Send";
	soap_tmp___tempuri__AnDan1Send.tempuri__AnDan1Send = tempuri__AnDan1Send;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan1Send(soap, &soap_tmp___tempuri__AnDan1Send);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan1Send(soap, &soap_tmp___tempuri__AnDan1Send, "-tempuri:AnDan1Send", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan1Send(soap, &soap_tmp___tempuri__AnDan1Send, "-tempuri:AnDan1Send", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan1SendResponse*>(&tempuri__AnDan1SendResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan1SendResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan1SendResponse.soap_get(soap, "tempuri:AnDan1SendResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan4UpdPeoplePresent(const char *endpoint, const char *soap_action, _tempuri__AnDan4UpdPeoplePresent *tempuri__AnDan4UpdPeoplePresent, _tempuri__AnDan4UpdPeoplePresentResponse &tempuri__AnDan4UpdPeoplePresentResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan4UpdPeoplePresent soap_tmp___tempuri__AnDan4UpdPeoplePresent;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan4UpdPeoplePresent";
	soap_tmp___tempuri__AnDan4UpdPeoplePresent.tempuri__AnDan4UpdPeoplePresent = tempuri__AnDan4UpdPeoplePresent;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan4UpdPeoplePresent(soap, &soap_tmp___tempuri__AnDan4UpdPeoplePresent);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan4UpdPeoplePresent(soap, &soap_tmp___tempuri__AnDan4UpdPeoplePresent, "-tempuri:AnDan4UpdPeoplePresent", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan4UpdPeoplePresent(soap, &soap_tmp___tempuri__AnDan4UpdPeoplePresent, "-tempuri:AnDan4UpdPeoplePresent", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan4UpdPeoplePresentResponse*>(&tempuri__AnDan4UpdPeoplePresentResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan4UpdPeoplePresentResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan4UpdPeoplePresentResponse.soap_get(soap, "tempuri:AnDan4UpdPeoplePresentResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan3AddUsers(const char *endpoint, const char *soap_action, _tempuri__AnDan3AddUsers *tempuri__AnDan3AddUsers, _tempuri__AnDan3AddUsersResponse &tempuri__AnDan3AddUsersResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan3AddUsers soap_tmp___tempuri__AnDan3AddUsers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan3AddUsers";
	soap_tmp___tempuri__AnDan3AddUsers.tempuri__AnDan3AddUsers = tempuri__AnDan3AddUsers;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan3AddUsers(soap, &soap_tmp___tempuri__AnDan3AddUsers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan3AddUsers(soap, &soap_tmp___tempuri__AnDan3AddUsers, "-tempuri:AnDan3AddUsers", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan3AddUsers(soap, &soap_tmp___tempuri__AnDan3AddUsers, "-tempuri:AnDan3AddUsers", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan3AddUsersResponse*>(&tempuri__AnDan3AddUsersResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan3AddUsersResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan3AddUsersResponse.soap_get(soap, "tempuri:AnDan3AddUsersResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan2PeoplePresent(const char *endpoint, const char *soap_action, _tempuri__AnDan2PeoplePresent *tempuri__AnDan2PeoplePresent, _tempuri__AnDan2PeoplePresentResponse &tempuri__AnDan2PeoplePresentResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan2PeoplePresent soap_tmp___tempuri__AnDan2PeoplePresent;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan2PeoplePresent";
	soap_tmp___tempuri__AnDan2PeoplePresent.tempuri__AnDan2PeoplePresent = tempuri__AnDan2PeoplePresent;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan2PeoplePresent(soap, &soap_tmp___tempuri__AnDan2PeoplePresent);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan2PeoplePresent(soap, &soap_tmp___tempuri__AnDan2PeoplePresent, "-tempuri:AnDan2PeoplePresent", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan2PeoplePresent(soap, &soap_tmp___tempuri__AnDan2PeoplePresent, "-tempuri:AnDan2PeoplePresent", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan2PeoplePresentResponse*>(&tempuri__AnDan2PeoplePresentResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan2PeoplePresentResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan2PeoplePresentResponse.soap_get(soap, "tempuri:AnDan2PeoplePresentResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDanSLTypeGet(const char *endpoint, const char *soap_action, _tempuri__AnDanSLTypeGet *tempuri__AnDanSLTypeGet, _tempuri__AnDanSLTypeGetResponse &tempuri__AnDanSLTypeGetResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDanSLTypeGet soap_tmp___tempuri__AnDanSLTypeGet;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDanSLTypeGet";
	soap_tmp___tempuri__AnDanSLTypeGet.tempuri__AnDanSLTypeGet = tempuri__AnDanSLTypeGet;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDanSLTypeGet(soap, &soap_tmp___tempuri__AnDanSLTypeGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDanSLTypeGet(soap, &soap_tmp___tempuri__AnDanSLTypeGet, "-tempuri:AnDanSLTypeGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDanSLTypeGet(soap, &soap_tmp___tempuri__AnDanSLTypeGet, "-tempuri:AnDanSLTypeGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDanSLTypeGetResponse*>(&tempuri__AnDanSLTypeGetResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDanSLTypeGetResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDanSLTypeGetResponse.soap_get(soap, "tempuri:AnDanSLTypeGetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDanSLTypeAdd(const char *endpoint, const char *soap_action, _tempuri__AnDanSLTypeAdd *tempuri__AnDanSLTypeAdd, _tempuri__AnDanSLTypeAddResponse &tempuri__AnDanSLTypeAddResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDanSLTypeAdd soap_tmp___tempuri__AnDanSLTypeAdd;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDanSLTypeAdd";
	soap_tmp___tempuri__AnDanSLTypeAdd.tempuri__AnDanSLTypeAdd = tempuri__AnDanSLTypeAdd;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDanSLTypeAdd(soap, &soap_tmp___tempuri__AnDanSLTypeAdd);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDanSLTypeAdd(soap, &soap_tmp___tempuri__AnDanSLTypeAdd, "-tempuri:AnDanSLTypeAdd", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDanSLTypeAdd(soap, &soap_tmp___tempuri__AnDanSLTypeAdd, "-tempuri:AnDanSLTypeAdd", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDanSLTypeAddResponse*>(&tempuri__AnDanSLTypeAddResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDanSLTypeAddResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDanSLTypeAddResponse.soap_get(soap, "tempuri:AnDanSLTypeAddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::GetDate_(const char *endpoint, const char *soap_action, _tempuri__GetDate *tempuri__GetDate, _tempuri__GetDateResponse &tempuri__GetDateResponse)
{	struct soap *soap = this;
	struct __tempuri__GetDate_ soap_tmp___tempuri__GetDate_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetDate";
	soap_tmp___tempuri__GetDate_.tempuri__GetDate = tempuri__GetDate;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetDate_(soap, &soap_tmp___tempuri__GetDate_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetDate_(soap, &soap_tmp___tempuri__GetDate_, "-tempuri:GetDate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetDate_(soap, &soap_tmp___tempuri__GetDate_, "-tempuri:GetDate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetDateResponse*>(&tempuri__GetDateResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetDateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetDateResponse.soap_get(soap, "tempuri:GetDateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::GetDocCode_(const char *endpoint, const char *soap_action, _tempuri__GetDocCode *tempuri__GetDocCode, _tempuri__GetDocCodeResponse &tempuri__GetDocCodeResponse)
{	struct soap *soap = this;
	struct __tempuri__GetDocCode_ soap_tmp___tempuri__GetDocCode_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetDocCode";
	soap_tmp___tempuri__GetDocCode_.tempuri__GetDocCode = tempuri__GetDocCode;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetDocCode_(soap, &soap_tmp___tempuri__GetDocCode_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetDocCode_(soap, &soap_tmp___tempuri__GetDocCode_, "-tempuri:GetDocCode", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetDocCode_(soap, &soap_tmp___tempuri__GetDocCode_, "-tempuri:GetDocCode", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetDocCodeResponse*>(&tempuri__GetDocCodeResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetDocCodeResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetDocCodeResponse.soap_get(soap, "tempuri:GetDocCodeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::ToolingTimes_(const char *endpoint, const char *soap_action, _tempuri__ToolingTimes *tempuri__ToolingTimes, _tempuri__ToolingTimesResponse &tempuri__ToolingTimesResponse)
{	struct soap *soap = this;
	struct __tempuri__ToolingTimes_ soap_tmp___tempuri__ToolingTimes_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ToolingTimes";
	soap_tmp___tempuri__ToolingTimes_.tempuri__ToolingTimes = tempuri__ToolingTimes;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__ToolingTimes_(soap, &soap_tmp___tempuri__ToolingTimes_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__ToolingTimes_(soap, &soap_tmp___tempuri__ToolingTimes_, "-tempuri:ToolingTimes", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__ToolingTimes_(soap, &soap_tmp___tempuri__ToolingTimes_, "-tempuri:ToolingTimes", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__ToolingTimesResponse*>(&tempuri__ToolingTimesResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__ToolingTimesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__ToolingTimesResponse.soap_get(soap, "tempuri:ToolingTimesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::WorkOrder_(const char *endpoint, const char *soap_action, _tempuri__WorkOrder *tempuri__WorkOrder, _tempuri__WorkOrderResponse &tempuri__WorkOrderResponse)
{	struct soap *soap = this;
	struct __tempuri__WorkOrder_ soap_tmp___tempuri__WorkOrder_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/WorkOrder";
	soap_tmp___tempuri__WorkOrder_.tempuri__WorkOrder = tempuri__WorkOrder;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__WorkOrder_(soap, &soap_tmp___tempuri__WorkOrder_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__WorkOrder_(soap, &soap_tmp___tempuri__WorkOrder_, "-tempuri:WorkOrder", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__WorkOrder_(soap, &soap_tmp___tempuri__WorkOrder_, "-tempuri:WorkOrder", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__WorkOrderResponse*>(&tempuri__WorkOrderResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__WorkOrderResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__WorkOrderResponse.soap_get(soap, "tempuri:WorkOrderResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::LineInventory_(const char *endpoint, const char *soap_action, _tempuri__LineInventory *tempuri__LineInventory, _tempuri__LineInventoryResponse &tempuri__LineInventoryResponse)
{	struct soap *soap = this;
	struct __tempuri__LineInventory_ soap_tmp___tempuri__LineInventory_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/LineInventory";
	soap_tmp___tempuri__LineInventory_.tempuri__LineInventory = tempuri__LineInventory;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__LineInventory_(soap, &soap_tmp___tempuri__LineInventory_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__LineInventory_(soap, &soap_tmp___tempuri__LineInventory_, "-tempuri:LineInventory", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__LineInventory_(soap, &soap_tmp___tempuri__LineInventory_, "-tempuri:LineInventory", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LineInventoryResponse*>(&tempuri__LineInventoryResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LineInventoryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LineInventoryResponse.soap_get(soap, "tempuri:LineInventoryResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::LineInventoryUpdate_(const char *endpoint, const char *soap_action, _tempuri__LineInventoryUpdate *tempuri__LineInventoryUpdate, _tempuri__LineInventoryUpdateResponse &tempuri__LineInventoryUpdateResponse)
{	struct soap *soap = this;
	struct __tempuri__LineInventoryUpdate_ soap_tmp___tempuri__LineInventoryUpdate_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/LineInventoryUpdate";
	soap_tmp___tempuri__LineInventoryUpdate_.tempuri__LineInventoryUpdate = tempuri__LineInventoryUpdate;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__LineInventoryUpdate_(soap, &soap_tmp___tempuri__LineInventoryUpdate_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__LineInventoryUpdate_(soap, &soap_tmp___tempuri__LineInventoryUpdate_, "-tempuri:LineInventoryUpdate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__LineInventoryUpdate_(soap, &soap_tmp___tempuri__LineInventoryUpdate_, "-tempuri:LineInventoryUpdate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LineInventoryUpdateResponse*>(&tempuri__LineInventoryUpdateResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LineInventoryUpdateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LineInventoryUpdateResponse.soap_get(soap, "tempuri:LineInventoryUpdateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::LineInventoryReturn_(const char *endpoint, const char *soap_action, _tempuri__LineInventoryReturn *tempuri__LineInventoryReturn, _tempuri__LineInventoryReturnResponse &tempuri__LineInventoryReturnResponse)
{	struct soap *soap = this;
	struct __tempuri__LineInventoryReturn_ soap_tmp___tempuri__LineInventoryReturn_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/LineInventoryReturn";
	soap_tmp___tempuri__LineInventoryReturn_.tempuri__LineInventoryReturn = tempuri__LineInventoryReturn;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__LineInventoryReturn_(soap, &soap_tmp___tempuri__LineInventoryReturn_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__LineInventoryReturn_(soap, &soap_tmp___tempuri__LineInventoryReturn_, "-tempuri:LineInventoryReturn", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__LineInventoryReturn_(soap, &soap_tmp___tempuri__LineInventoryReturn_, "-tempuri:LineInventoryReturn", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LineInventoryReturnResponse*>(&tempuri__LineInventoryReturnResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LineInventoryReturnResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LineInventoryReturnResponse.soap_get(soap, "tempuri:LineInventoryReturnResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::ItemsAdd_(const char *endpoint, const char *soap_action, _tempuri__ItemsAdd *tempuri__ItemsAdd, _tempuri__ItemsAddResponse &tempuri__ItemsAddResponse)
{	struct soap *soap = this;
	struct __tempuri__ItemsAdd_ soap_tmp___tempuri__ItemsAdd_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ItemsAdd";
	soap_tmp___tempuri__ItemsAdd_.tempuri__ItemsAdd = tempuri__ItemsAdd;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__ItemsAdd_(soap, &soap_tmp___tempuri__ItemsAdd_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__ItemsAdd_(soap, &soap_tmp___tempuri__ItemsAdd_, "-tempuri:ItemsAdd", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__ItemsAdd_(soap, &soap_tmp___tempuri__ItemsAdd_, "-tempuri:ItemsAdd", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__ItemsAddResponse*>(&tempuri__ItemsAddResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__ItemsAddResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__ItemsAddResponse.soap_get(soap, "tempuri:ItemsAddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::DocAdd_(const char *endpoint, const char *soap_action, _tempuri__DocAdd *tempuri__DocAdd, _tempuri__DocAddResponse &tempuri__DocAddResponse)
{	struct soap *soap = this;
	struct __tempuri__DocAdd_ soap_tmp___tempuri__DocAdd_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/DocAdd";
	soap_tmp___tempuri__DocAdd_.tempuri__DocAdd = tempuri__DocAdd;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__DocAdd_(soap, &soap_tmp___tempuri__DocAdd_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__DocAdd_(soap, &soap_tmp___tempuri__DocAdd_, "-tempuri:DocAdd", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__DocAdd_(soap, &soap_tmp___tempuri__DocAdd_, "-tempuri:DocAdd", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__DocAddResponse*>(&tempuri__DocAddResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__DocAddResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__DocAddResponse.soap_get(soap, "tempuri:DocAddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::GetDept_(const char *endpoint, const char *soap_action, _tempuri__GetDept *tempuri__GetDept, _tempuri__GetDeptResponse &tempuri__GetDeptResponse)
{	struct soap *soap = this;
	struct __tempuri__GetDept_ soap_tmp___tempuri__GetDept_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetDept";
	soap_tmp___tempuri__GetDept_.tempuri__GetDept = tempuri__GetDept;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetDept_(soap, &soap_tmp___tempuri__GetDept_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetDept_(soap, &soap_tmp___tempuri__GetDept_, "-tempuri:GetDept", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetDept_(soap, &soap_tmp___tempuri__GetDept_, "-tempuri:GetDept", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetDeptResponse*>(&tempuri__GetDeptResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetDeptResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetDeptResponse.soap_get(soap, "tempuri:GetDeptResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::GetPower_(const char *endpoint, const char *soap_action, _tempuri__GetPower *tempuri__GetPower, _tempuri__GetPowerResponse &tempuri__GetPowerResponse)
{	struct soap *soap = this;
	struct __tempuri__GetPower_ soap_tmp___tempuri__GetPower_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetPower";
	soap_tmp___tempuri__GetPower_.tempuri__GetPower = tempuri__GetPower;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__GetPower_(soap, &soap_tmp___tempuri__GetPower_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__GetPower_(soap, &soap_tmp___tempuri__GetPower_, "-tempuri:GetPower", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__GetPower_(soap, &soap_tmp___tempuri__GetPower_, "-tempuri:GetPower", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__GetPowerResponse*>(&tempuri__GetPowerResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__GetPowerResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__GetPowerResponse.soap_get(soap, "tempuri:GetPowerResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::Login_(const char *endpoint, const char *soap_action, _tempuri__Login *tempuri__Login, _tempuri__LoginResponse &tempuri__LoginResponse)
{	struct soap *soap = this;
	struct __tempuri__Login_ soap_tmp___tempuri__Login_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Login";
	soap_tmp___tempuri__Login_.tempuri__Login = tempuri__Login;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__Login_(soap, &soap_tmp___tempuri__Login_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__Login_(soap, &soap_tmp___tempuri__Login_, "-tempuri:Login", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__Login_(soap, &soap_tmp___tempuri__Login_, "-tempuri:Login", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__LoginResponse*>(&tempuri__LoginResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__LoginResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__LoginResponse.soap_get(soap, "tempuri:LoginResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan1Send_(const char *endpoint, const char *soap_action, _tempuri__AnDan1Send *tempuri__AnDan1Send, _tempuri__AnDan1SendResponse &tempuri__AnDan1SendResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan1Send_ soap_tmp___tempuri__AnDan1Send_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan1Send";
	soap_tmp___tempuri__AnDan1Send_.tempuri__AnDan1Send = tempuri__AnDan1Send;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan1Send_(soap, &soap_tmp___tempuri__AnDan1Send_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan1Send_(soap, &soap_tmp___tempuri__AnDan1Send_, "-tempuri:AnDan1Send", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan1Send_(soap, &soap_tmp___tempuri__AnDan1Send_, "-tempuri:AnDan1Send", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan1SendResponse*>(&tempuri__AnDan1SendResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan1SendResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan1SendResponse.soap_get(soap, "tempuri:AnDan1SendResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan4UpdPeoplePresent_(const char *endpoint, const char *soap_action, _tempuri__AnDan4UpdPeoplePresent *tempuri__AnDan4UpdPeoplePresent, _tempuri__AnDan4UpdPeoplePresentResponse &tempuri__AnDan4UpdPeoplePresentResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan4UpdPeoplePresent_ soap_tmp___tempuri__AnDan4UpdPeoplePresent_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan4UpdPeoplePresent";
	soap_tmp___tempuri__AnDan4UpdPeoplePresent_.tempuri__AnDan4UpdPeoplePresent = tempuri__AnDan4UpdPeoplePresent;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan4UpdPeoplePresent_(soap, &soap_tmp___tempuri__AnDan4UpdPeoplePresent_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan4UpdPeoplePresent_(soap, &soap_tmp___tempuri__AnDan4UpdPeoplePresent_, "-tempuri:AnDan4UpdPeoplePresent", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan4UpdPeoplePresent_(soap, &soap_tmp___tempuri__AnDan4UpdPeoplePresent_, "-tempuri:AnDan4UpdPeoplePresent", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan4UpdPeoplePresentResponse*>(&tempuri__AnDan4UpdPeoplePresentResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan4UpdPeoplePresentResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan4UpdPeoplePresentResponse.soap_get(soap, "tempuri:AnDan4UpdPeoplePresentResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan3AddUsers_(const char *endpoint, const char *soap_action, _tempuri__AnDan3AddUsers *tempuri__AnDan3AddUsers, _tempuri__AnDan3AddUsersResponse &tempuri__AnDan3AddUsersResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan3AddUsers_ soap_tmp___tempuri__AnDan3AddUsers_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan3AddUsers";
	soap_tmp___tempuri__AnDan3AddUsers_.tempuri__AnDan3AddUsers = tempuri__AnDan3AddUsers;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan3AddUsers_(soap, &soap_tmp___tempuri__AnDan3AddUsers_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan3AddUsers_(soap, &soap_tmp___tempuri__AnDan3AddUsers_, "-tempuri:AnDan3AddUsers", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan3AddUsers_(soap, &soap_tmp___tempuri__AnDan3AddUsers_, "-tempuri:AnDan3AddUsers", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan3AddUsersResponse*>(&tempuri__AnDan3AddUsersResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan3AddUsersResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan3AddUsersResponse.soap_get(soap, "tempuri:AnDan3AddUsersResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDan2PeoplePresent_(const char *endpoint, const char *soap_action, _tempuri__AnDan2PeoplePresent *tempuri__AnDan2PeoplePresent, _tempuri__AnDan2PeoplePresentResponse &tempuri__AnDan2PeoplePresentResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDan2PeoplePresent_ soap_tmp___tempuri__AnDan2PeoplePresent_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDan2PeoplePresent";
	soap_tmp___tempuri__AnDan2PeoplePresent_.tempuri__AnDan2PeoplePresent = tempuri__AnDan2PeoplePresent;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDan2PeoplePresent_(soap, &soap_tmp___tempuri__AnDan2PeoplePresent_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDan2PeoplePresent_(soap, &soap_tmp___tempuri__AnDan2PeoplePresent_, "-tempuri:AnDan2PeoplePresent", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDan2PeoplePresent_(soap, &soap_tmp___tempuri__AnDan2PeoplePresent_, "-tempuri:AnDan2PeoplePresent", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDan2PeoplePresentResponse*>(&tempuri__AnDan2PeoplePresentResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDan2PeoplePresentResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDan2PeoplePresentResponse.soap_get(soap, "tempuri:AnDan2PeoplePresentResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDanSLTypeGet_(const char *endpoint, const char *soap_action, _tempuri__AnDanSLTypeGet *tempuri__AnDanSLTypeGet, _tempuri__AnDanSLTypeGetResponse &tempuri__AnDanSLTypeGetResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDanSLTypeGet_ soap_tmp___tempuri__AnDanSLTypeGet_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDanSLTypeGet";
	soap_tmp___tempuri__AnDanSLTypeGet_.tempuri__AnDanSLTypeGet = tempuri__AnDanSLTypeGet;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDanSLTypeGet_(soap, &soap_tmp___tempuri__AnDanSLTypeGet_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDanSLTypeGet_(soap, &soap_tmp___tempuri__AnDanSLTypeGet_, "-tempuri:AnDanSLTypeGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDanSLTypeGet_(soap, &soap_tmp___tempuri__AnDanSLTypeGet_, "-tempuri:AnDanSLTypeGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDanSLTypeGetResponse*>(&tempuri__AnDanSLTypeGetResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDanSLTypeGetResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDanSLTypeGetResponse.soap_get(soap, "tempuri:AnDanSLTypeGetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int MESServiceSoapProxy::AnDanSLTypeAdd_(const char *endpoint, const char *soap_action, _tempuri__AnDanSLTypeAdd *tempuri__AnDanSLTypeAdd, _tempuri__AnDanSLTypeAddResponse &tempuri__AnDanSLTypeAddResponse)
{	struct soap *soap = this;
	struct __tempuri__AnDanSLTypeAdd_ soap_tmp___tempuri__AnDanSLTypeAdd_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.1.26:801/MESService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AnDanSLTypeAdd";
	soap_tmp___tempuri__AnDanSLTypeAdd_.tempuri__AnDanSLTypeAdd = tempuri__AnDanSLTypeAdd;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___tempuri__AnDanSLTypeAdd_(soap, &soap_tmp___tempuri__AnDanSLTypeAdd_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__AnDanSLTypeAdd_(soap, &soap_tmp___tempuri__AnDanSLTypeAdd_, "-tempuri:AnDanSLTypeAdd", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__AnDanSLTypeAdd_(soap, &soap_tmp___tempuri__AnDanSLTypeAdd_, "-tempuri:AnDanSLTypeAdd", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_tempuri__AnDanSLTypeAddResponse*>(&tempuri__AnDanSLTypeAddResponse)) // NULL ref?
		return soap_closesock(soap);
	tempuri__AnDanSLTypeAddResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__AnDanSLTypeAddResponse.soap_get(soap, "tempuri:AnDanSLTypeAddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
